/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var o=Object.defineProperty;var c=Object.getOwnPropertyDescriptor;var s=Object.getOwnPropertyNames;var g=Object.prototype.hasOwnProperty;var r=(l,e)=>{for(var a in e)o(l,a,{get:e[a],enumerable:!0})},u=(l,e,a,n)=>{if(e&&typeof e=="object"||typeof e=="function")for(let t of s(e))!g.call(l,t)&&t!==a&&o(l,t,{get:()=>e[t],enumerable:!(n=c(e,t))||n.enumerable});return l};var m=l=>u(o({},"__esModule",{value:!0}),l);var p={};r(p,{default:()=>i});module.exports=m(p);var d=require("obsidian"),i=class extends d.Plugin{async onload(){this.addCommand({id:"duplicate-line",name:"Duplicate line",editorCallback:(e,a)=>{if(e.somethingSelected()){let n=e.getSelection();e.replaceSelection(n+n)}else{let n=e.getCursor(),t=e.getLine(n.line);e.setLine(n.line,t+`
`+t)}}})}onunload(){}};

/* nosourcemap */